#!/bin/sh
#
# clean.sh — removes every file generated by building or running cpre,
#            restoring the project to its pristine (source-only) state.
#
# It deletes:
#   - build artifacts         : the cpre executable and src/*.o object files
#   - runtime output files    : o.txt, output.c and *.out (project root and tests/)
#   - OS / debugger leftovers  : *.dSYM bundles and .DS_Store files (macOS, skipped on Linux)
#
# Portable POSIX sh: runs on both Linux and macOS.
# Usage:  sh clean.sh    (or:  make clean)

set -eu

# Run from the project root, regardless of where the script is called from.
cd "$(dirname "$0")"

removed=0

# remove PATH... — deletes each path that actually exists and reports it.
# The [ -e ] guard means unmatched globs (left literal by the shell) are skipped,
# so nothing is ever deleted by accident.
remove() {
    for target in "$@"; do
        if [ -e "$target" ]; then
            rm -rf "$target"
            printf '  removed %s\n' "$target"
            removed=$((removed + 1))
        fi
    done
}

echo "Cleaning generated files..."

# Build artifacts
remove cpre
for obj in src/*.o; do remove "$obj"; done

# Runtime output files (the conventional names used in the docs)
remove o.txt output.c tests/o.txt tests/output.c
for out in ./*.out tests/*.out; do remove "$out"; done

# OS / debugger leftovers
for bundle in ./*.dSYM tests/*.dSYM; do remove "$bundle"; done
remove .DS_Store src/.DS_Store tests/.DS_Store

if [ "$removed" -eq 0 ]; then
    echo "Already clean — nothing to remove."
else
    echo "Done ($removed item(s) removed)."
fi